from dotenv import load_dotenv
import os
import sys
import subprocess
from langgraph.graph import StateGraph, END
from typing import TypedDict, List
from langchain_core.messages import  SystemMessage, HumanMessage, ToolMessage
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from src.utils.logger import log_experiment, ActionType


# --- 1. THE AGENT STATE ---
class AgentState(TypedDict):
    """The shared state of the Swarm. Stores the conversation history and the plan."""
    messages: List[str]      # Chat history ( y7fd l base message)
    target_dir: str          # The folder we are fixing
    analysis_report: str     # Output from Pylint (Raw text)
    refactoring_plan: str    # The final JSON plan generated by Auditor ( bch ymedo ll action agent)
    iteration_count: int     # To avoid infinite loops

# --- 2. THE TOOLSMITH SECTION ---

@tool
def run_pylint_tool(target_dir: str) -> str:
    """
    Run Pylint static analysis on the target directory.
    
    Args:
        target_dir: Path to the directory to analyze
        
    Returns:
        Pylint analysis output as a string
    """
    if not os.path.exists(target_dir):
        return f"Error: Directory {target_dir} does not exist."
    
    result = subprocess.run(
            ["pylint", target_dir, "--persistent=n", "--score=y"],
            capture_output=True,
            text=True,
            check=False # Pylint returns non-zero codes for errors, we don't want it to crash our script
        )
    
   
    return result.stdout 

# --- 3. THE AUDITOR AGENT NODE ---
def auditor_node(state: AgentState):
    """
    The Auditor reads the code, runs analysis, and generates a plan.
    """
    print("--- AUDITOR: Starting Analysis ---")
    
    
    analysis_result = run_pylint_tool.invoke({"target_dir": state['target_dir']})
    
    # Step B: Prompt Engineering (The Brain)
    system_prompt = """
    You are The Auditor, a Senior QA Engineer.
    Your goal is to analyze the following static analysis report and create a Refactoring Plan.
    
    Output Format: JSON with keys 'files_to_fix', 'description_of_fix'.
    Do not be chatty. Only output JSON.
    """
    
    user_content = f"Here is the Pylint report:\n{analysis_result}"
    
    # Call the LLM (Replace with your specific model initialization)
    llm = ChatOpenAI(
        model="qwen/qwen2.5-coder-32b-instruct", 
        temperature=0,
        base_url=os.getenv("OPENAI_BASE_URL"),
        api_key=os.getenv("OPENAI_API_KEY")
    )
    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_content)
    ])
    
    # --- 4. CRITICAL: DATA OFFICER LOGGING ---
    
    try:
        log_experiment(
            agent_name="Auditor",
            model_used="qwen/qwen2.5-coder-32b-instruct",
            action=ActionType.ANALYSIS, 
            details={
                "input_prompt": system_prompt + user_content, 
                "output_response": response.content,          
                "target_dir": state['target_dir']
            },
            status="SUCCESS"
        )
    except Exception as e:
        print(f"Logging failed: {e}")

    
    return {
        "analysis_report": analysis_result,
        "refactoring_plan": response.content,
        "messages": [response]
    }

# This function will later be added to your LangGraph workflow
# workflow.add_node("auditor", auditor_node)